### ISSUE TITLE
[FEAT] Home UI 구현 (카드 셀 제외)

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#1]
## 💡 Issue
지도가 있는 Home 화면의 UI를 구성합니다 (하단의 카드 셀은 제외합니다)

## 📝  todo
- [x] 공통 사용 이미지 literal 만들기
- [x] image asset 추가
- [x] color, font extension에 추가
- [x] 상단의 주소를 나타내는 박스 구현
- [x] 네이버 지도 구현
- [x] 목록 보기 버튼 UI 구현
- [x] 현재 기준 다시 검색 버튼 UI 구현
- [x] collection view cell UI
- [x] collection view 매장 없음 cell UI
- [x] collection view carousel 구현

## 📸 Screenshot
<img width="300" alt="스크린샷 2022-09-19 오후 9 00 30" src="https://user-images.githubusercontent.com/26588989/191014020-e177bd62-3515-477d-9552-3aea55d06378.png">
