### ISSUE TITLE
[FEAT] 가게 정보 나타내는 모달 전반적인 UI와 collectionView

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#19]
## 💡 Issue
가게 정보 나타내는 모달의 UI 완성

## 📝  todo
- [x] 상단 타이틀
- [x] 가게 종류 나타내는 collectionView UI
- [x] 필터 기능을 하는 버튼 UI
- [x] 지도로 돌아갈 수 있는 UI

## 📸 Screenshot
<img width="300" alt="스크린샷 2022-10-11 오후 8 33 40" src="https://user-images.githubusercontent.com/26588989/195079568-7befad4a-a450-414d-9a3a-b903e4eb3e09.png">
