### ISSUE TITLE
[FEAT] 가게 정보를 나타내는 모달의 필터 버튼 기능 구현

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#22]
## 💡 Issue
필터 버튼과 정렬 버튼 기능 구현

## 📝  todo
- [x] 포포팟 코드 참고하여 필터, 정렬 코드 어떻게 분리할 것인지 고민
- [x] 필터 버튼 기능 구현
- [ ] 정렬 버튼 기능 구현

## 📸 Screenshot

<img width="300" alt="스크린샷 2022-10-11 오후 8 33 40" src="https://user-images.githubusercontent.com/26588989/195079568-7befad4a-a450-414d-9a3a-b903e4eb3e09.png">
