### ISSUE TITLE
[FEAT] 상세 정보 View

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#23]
## 💡 Issue
상세정보 View UI 작성

## 📝  todo
- [x] 지도 로드
- [x] 가게 정보 카드 UI
- [x] 주소 복사 toast message
- [x] 가게 정보 UI
- [x] 정보 수정, 후기 작성 공통 button

## 📸 Screenshot

<img width="215" alt="스크린샷 2022-10-19 오후 10 17 31" src="https://user-images.githubusercontent.com/26588989/196701995-0225cd38-020a-4f7c-bffa-208c1c992096.png">
