### ISSUE TITLE
[FEAT] firebase useCase, Repository 작성

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#29]
## 💡 Issue
firebase 사용에 필요한 repository, useCase 작성

## 📝  todo
- [ ] 가게 찜하기 useCase
- [ ] 가게 정보(별점, 찜한 인원) 관련 crud useCase
- [ ] 가게 상세 정보 crud useCase
- [ ] 후기 cr useCase
- [ ] 특정 댓글에 대한 도움 +1 useCase
- [ ] 계정 닉네임 useCase
