### ISSUE TITLE
[FEAT] 다시 검색, 현재 위치 이동 기능

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#3]
## 💡 Issue
- 지도의 카메라가 이동되었을 때 다시 검색하는 기능 구현
- 현재 위치로 이동하는 버튼의 기능 구현

## 📝  todo
- [x] 카메라가 이동됨에 따라 "다시 검색" 버튼이 뜨도록 구현
- [x] 현재 위치로 이동하는 버튼 UI 구현
- [x] 현재 위치로 이동하는 버튼 기능 구현

## 📸 Screenshot
<img width="300" alt="스크린샷 2022-09-19 오후 9 15 40" src="https://user-images.githubusercontent.com/26588989/191015591-3c885921-f55f-45d7-b902-958ec67fa5c7.png">
