### ISSUE TITLE
[FEAT] 상세 정보 수정 UI

### ISSUE THREAD

**Issue by SH0123** [SH0123/NEMO-fourcut-map-ios#33]
## 💡 Issue
상세 정보 수정 UI 구현

## 📝  todo
- [ ] 폐점 신고 버튼 
- [ ] 단일 선택 버튼 구현
- [ ] 다중 선택 버튼 구현
- [ ] TextView 구현

## 📸 Screenshot

<img width="300" alt="스크린샷 2022-10-25 오후 6 47 32" src="https://user-images.githubusercontent.com/26588989/197741650-f2fec3a7-d834-4684-9084-5dae80f83487.png">
